function(search_for_header headers result)
    foreach(header IN LISTS headers)
        string(MAKE_C_IDENTIFIER "${header}" header_id)
        string(TOUPPER "${header_id}" header_id)
        check_include_file("${header}" "HAVE_${header_id}")
        if(HAVE_${header_id})
            set(${result} "${header}" PARENT_SCOPE)
            return()
        endif()
    endforeach()
    set(${result} "" PARENT_SCOPE)
endfunction()
