function(search_for_function function libraries target result)
    check_function_exists("${function}" "${result}_IN_LIBC")
    if(${result}_IN_LIBC)
        set(${result} 1 PARENT_SCOPE)
        return()
    endif()

    foreach(library IN LISTS libraries)
        string(MAKE_C_IDENTIFIER "${library}" library_id)
        string(TOUPPER "${library_id}" library_id)
        check_library_exists("${library}" "${function}" ""
            "${result}_IN_${library_id}")
        if(${result}_IN_${library_id})
            target_link_libraries(${target} PRIVATE "${library}")
            set(${result} 1 PARENT_SCOPE)
            return()
        endif()
    endforeach()

    set(${result} 0 PARENT_SCOPE)
endfunction()

function(check_headers_break headers)
    foreach(header IN LISTS headers)
        string(MAKE_C_IDENTIFIER "${header}" header_id)
        string(TOUPPER "${header_id}" header_id)
        check_include_file("${header}" "HAVE_${header_id}")
        if(HAVE_${header_id})
            set("HAVE_${header_id}" 1 PARENT_SCOPE)
            return()
        endif()
    endforeach()
endfunction()
