# Installation for Tinyfugue

set(CMAKE_INSTALL_MESSAGE NEVER)

if (CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
    execute_process(COMMAND test -w ${CMAKE_INSTALL_FULL_PREFIX}/bin -a -w ${CMAKE_INSTALL_FULL_PREFIX}/share
        RESULT_VARIABLE DEST_DIR_WRITABLE)
    if (NOT DEST_DIR_WRITABLE EQUAL 0)
        set(CMAKE_INSTALL_PREFIX "$ENV{HOME}" CACHE PATH "Where to install the distribution" FORCE)
    endif (NOT DEST_DIR_WRITABLE EQUAL 0)
endif (CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)

set(prefix ${CMAKE_INSTALL_PREFIX})
set(bindir ${CMAKE_INSTALL_FULL_BINDIR})
set(mandir ${CMAKE_INSTALL_FULL_MANDIR})
set(datadir ${CMAKE_INSTALL_FULL_DATAROOTDIR})

install(TARGETS tf
        PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ
                    GROUP_EXECUTE WORLD_READ WORLD_EXECUTE
        DESTINATION ${bindir})

install(DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/tf-lib/
        DESTINATION ${datadir}/${LIBNAME}
        FILES_MATCHING PATTERN "*")

install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/src/tf.1.nroffman DESTINATION ${mandir}/man1 RENAME tf.1)
