install(TARGETS tf
    RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}"
    PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE
                GROUP_READ GROUP_EXECUTE
                WORLD_READ WORLD_EXECUTE)

install(DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/tf-lib/"
    DESTINATION "${CMAKE_INSTALL_DATAROOTDIR}/${LIBNAME}"
    USE_SOURCE_PERMISSIONS
    PATTERN ".stamp" EXCLUDE
)

install(FILES "${CMAKE_CURRENT_SOURCE_DIR}/CHANGES"
    DESTINATION "${CMAKE_INSTALL_DATAROOTDIR}/${LIBNAME}")

install(FILES "${CMAKE_CURRENT_SOURCE_DIR}/src/tf.1.nroffman"
    DESTINATION "${CMAKE_INSTALL_MANDIR}/man1"
    RENAME "${EXENAME}.1")

if(TF_INSTALL_SYMLINK AND NOT EXENAME STREQUAL "tf")
    install(CODE "
        file(MAKE_DIRECTORY \"\$ENV{DESTDIR}\${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_BINDIR}\")
        file(REMOVE \"\$ENV{DESTDIR}\${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_BINDIR}/tf${CMAKE_EXECUTABLE_SUFFIX}\")
        file(CREATE_LINK
            \"${EXENAME}${CMAKE_EXECUTABLE_SUFFIX}\"
            \"\$ENV{DESTDIR}\${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_BINDIR}/tf${CMAKE_EXECUTABLE_SUFFIX}\"
            SYMBOLIC)")
endif()
