---
name: Continuous Integration

on:
  push:
    branches: [widechar, cmake]
  pull_request:
    branches: [widechar, cmake]
  schedule:
    - cron: '31 5 * * *'

jobs:
  build:

    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install required packages (apt)
        if: ${{ matrix.runner }} == "ubuntu-latest"
        run: |
          sudo apt-get update
          sudo apt-get install -q -y \
              make \
              cmake \
              g++ \
              libssl-dev \
              libncurses-dev \
              libicu-dev \
              libpcre3-dev

      - name: Install required packages (Homebrew)
        if: ${{ matrix.runner }} == "macos-latest"
        run: |
          brew install icu4c pcre

      - name: Run build
        run: make
