---
name: Continuous Integration

on:
  push:
    branches: [widechar, cmake]
  pull_request:
    branches: [widechar, cmake]
  schedule:
    - cron: '31 5 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install required packages
        run: sudo apt-get install -q -y make cmake g++ libssl-dev libncurses-dev libicu-dev libpcre3-dev
      - name: configure
        run: ./configure
      - name: make
        run: make
