---
name: Continuous Integration

on:
  push:
    branches: [widechar]
  pull_request:
    branches: [widechar]
  schedule:
    - cron: '31 5 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: ./configure
      - name: make
        run: make
