---
name: Portability

on:
  schedule:
    - cron: '31 5 * * *'
  workflow_dispatch:

concurrency:
  group: portability-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: NetBSD
            action: netbsd
          - name: OpenBSD
            action: openbsd
          - name: Solaris
            action: solaris
    steps:
      - name: Checkout source
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: NetBSD build
        if: matrix.action == 'netbsd'
        uses: vmactions/netbsd-vm@fac0a63f3e5244c600cb9ca532d27ee774ecdb4b # v1.4.3
        with:
          usesh: true
          prepare: /usr/sbin/pkg_add -u cmake ninja-build pcre2 icu openssl ncurses
          run: |
            cmake -S . -B build -G Ninja -DBUILD_TESTING=ON
            cmake --build build
            ctest --test-dir build --output-on-failure
      - name: OpenBSD build
        if: matrix.action == 'openbsd'
        uses: vmactions/openbsd-vm@c941015845c0f0c429676840963dc63b226d4f69 # v1.4.5
        with:
          usesh: true
          prepare: |
            pkg_add -I -D installed cmake ninja pcre2 icu4c
            pkg_add -I -u cmake ninja pcre2 icu4c
          run: |
            cmake -S . -B build -G Ninja -DBUILD_TESTING=ON \
              -DTF_TLS=OFF
            cmake --build build
            ctest --test-dir build --output-on-failure
      - name: Solaris build
        if: matrix.action == 'solaris'
        uses: vmactions/solaris-vm@315163f088b66e55bbcc45928bd224d4973b2312 # v1.3.8
        with:
          release: 11.4-gcc
          usesh: true
          prepare: pkg install cmake ninja pcre2 developer/icu openssl ncurses
          run: |
            cmake -S . -B build -G Ninja -DBUILD_TESTING=ON
            cmake --build build
            ctest --test-dir build --output-on-failure
